_BASE_: "../Base-HOIRCNN-FPN.yaml"
MODEL:
  WEIGHTS: "./output/hico_det_pretrained.pkl"
  HOI_ON: True
  HOI_BOX_HEAD:
    ACTION_CLS_WEIGHTS: [10., 128.]
    ALLOW_PERSON_TO_PERSON: True
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.005
  STEPS: (40000, 80000)
  MAX_ITER: 100000
  CHECKPOINT_PERIOD: 1000
DATASETS:
  TRAIN: ("hico-det_train", )
  TEST: ("hico-det_test", )
